services:
  - type: web
    name: teamtrack-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: CORS_ORIGINS
        value: ${CORS_ORIGINS}
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /opt/render/project/src/backend/src/main/resources/firebase-service-account.json
